#!/bin/bash -e

# git hook to run a command after `git checkout` if a specified file was changed

# this is a file checkout – do nothing
[[ "$3" == '0' ]] && exit 0

# this is a git clone
[[ "$1" == '0000000000000000000000000000000000000000' ]] && exit 0

[[ -f .git/hooks/post-merge ]] && ORIG_HEAD=$1 HEAD=$2 .git/hooks/post-merge
