#!/bin/bash

# git hook to run a command after `git pull` if a specified file was changed

changed_files="$(git diff-tree -r --name-only --no-commit-id ORIG_HEAD HEAD)"

check_run() {
	echo "$changed_files" | grep --quiet "$1" && eval "$2"
}

# In this example it's used to run `yarn` if yarn.lock changed
check_run yarn.lock "kill -s USR1 $(cat /tmp/node-exec.sh.pid)" 1>/dev/null 2>&1 &
check_run Gemfile.lock "bundle" 1>/dev/null &
check_run "db/migrate" "sleep 10; bundle exec rails db:migrate" 1>/dev/null 2>&1 &
