#!/bin/bash -e

# git hook to run a command after `git checkout` if a specified file was changed

# this is a file checkout – do nothing
[[ "$3" == '0' ]] && exit

ORIG_HEAD=$1 HEAD=$2 .git/hooks/post-merge
