#!/bin/bash

protected_branches='master|production'
current_branch=$(git symbolic-ref HEAD | sed -e 's,.*/\(.*\),\1,')

if test $(echo "$current_branch" | grep -E $protected_branches | wc -l) != 0
then
    read -p "You're about to push ${current_branch}, is that what you intended? [y|n] " -r yn < /dev/tty
    echo $yn | grep ^[Yy]$ 1>/dev/null
    if [ $? -eq 0 ]
    then
        exit 0 # push will execute
    fi
    exit 1 # push will not execute
else
    exit 0 # push will execute
fi
