#!/bin/sh
# Taken from: https://gist.github.com/guilherme/9604324
# Check for console.log( that might accidentally be committed
# This file must be executable (chmod +x)

echo 'Pre-commit hook running...'

consoleregexp='debugger|pry|debug\(|console\.log|token|password|pwd|TOKEN|PASSWORD|PWD|secret|SECRET'
# CHECK
if test $(git diff --cached | grep -E $consoleregexp | wc -l) != 0
then
  exec git diff --cached --name-only | while read file; do grep -H -nE $consoleregexp "$file"; done
  read -p "Ocurrences of forbidden words found in the code. Continue? (y/n)" -r yn < /dev/tty
  echo $yn | grep ^[Yy]$ 1>/dev/null
  if [ $? -eq 0 ]
  then
    exit 0; # THE USER WANTS TO CONTINUE
  else
    exit 1; # THE USER DOESN'T WANT TO CONTINUE SO ABORT
  fi
fi
